chore: fix ape versions due to hardhat upgrade breaking changes
lidofinance/gate-seals pull request #28
Opened 2024-04-17 08:59 UTC by rkolpakov

2024-04-17 11:04 UTC, TheDZhon requested changes
Thank you for the collaborative effort :handshake: 

I'd suggest to address some minor issues before going further :pray:

2024-04-17 11:04 UTC, TheDZhon commented on README.md
> +- the pause duration set at costruction time is limited to infinite (uint256 max value).
```suggestion
- the pause duration is set at construction time and may be unlimited (if uint256 max value is used)
```

2024-04-17 11:04 UTC, TheDZhon commented on package.json
> +    "hardhat": "2.12.6"
Maybe bump the version?

2024-04-17 11:04 UTC, TheDZhon commented on package.json
>    "author": "Azat Serikov <azatsdev@gmail.com>",
add yourself too :stars:

2026-06-09 20:10 UTC, tamtamchik commented
Closed as outdated.

2026-06-09 20:10 UTC, closed without merging